version: '3.8'

services:    

  mysql:
    image: mysql:latest
    container_name: college-mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - college-network
    volumes:
      - mysql-data:/var/lib/mysql

    
  college-portal:
    build: ./public/college-portal
    container_name: college-portal
    ports:
      - "3000:3000"
    networks:
      - college-network
    depends_on:
      - mysql:
        condition: service_healthy

networks:
  college-network:
    driver: bridge

volumes:
  mysql-data:
